### ISSUE TITLE
fix: Typo in readme?

### ISSUE THREAD

**Issue by lucas-goldner** [renancaraujo/glowup_vibes#2]
**Description**

First, thanks for making this 😂.
I think in the readme you accidentally wrote .lowkey two times on the string API. 

**Steps To Reproduce**

Open ReadMe

**Expected Behavior**

For the examples it should use different functions

**Screenshots**

![image](https://github.com/renancaraujo/glowup_vibes/assets/65627237/1e6933aa-7ece-43ba-a469-e19311cc0540)

**Comment by renancaraujo** [comment]
Thanks for pointing those out!

**Comment by renancaraujo** [comment]
Fixed on #3
